name: Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        docker build . -t docker.pkg.github.com/${{GITHUB_REPOSITORY}}:latest
        docker push docker.pkg.github.com/${{GITHUB_REPOSITORY}}:latest
